name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1
    - name: set up JDK 20
      uses: actions/setup-java@v3.13.0
      with:
        java-version: '20'
        distribution: 'oracle'
        cache: gradle
    - name: Setup Kotlin
      uses: fwilhe2/setup-kotlin@0.9.0
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
